services:
  postgres:
    image: postgres:18
    container_name: fitness-postgres
    environment:
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongPassword
    ports:
      - "5436:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d fitness_tracker"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  minio:
    image: minio/minio
    container_name: fitness-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
        interval: 30s
        timeout: 20s
        retries: 3

  fitnesstracker.api:
    image: ${DOCKER_REGISTRY-}fitnesstrackerapi
    build:
      context: .  
      dockerfile: FitnessTracker.API/Dockerfile 
    ports:
      - "8090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__FitnessDbContext=Host=postgres;Port=5432;Database=fitness_tracker;Username=admin;Password=strongPassword
      - Minio__ServiceUrl=http://minio:9000
      - Minio__AccessKey=minio_admin
      - Minio__SecretKey=minio_password
      - Minio__BucketName=fitness-photos
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - fitnesstracker.api

volumes:
  postgres_data:
  minio_data: